name: Docker Image CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2 
    - name: docker login
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Build the Docker image
      run: |
          docker build . --file Dockerfile --tag image0.20:$(date +%s)
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/newtask1
      
      
   
      
