name: Docker Image CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2 
    - name: docker login
      uses: docker/login-action@v1
      with: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
       context: .
       file: ./Dockerfile
       push: true
       tags: mytask/my-image0.10:latest
