name: CI
on:
  push:
  pull_request:
jobs:
  build:
   runs-on: windows-latest
   steps:
      - uses: actions/checkout@v2
        name: set-up java
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
      - name: Run tests with Maven-[]
        run: mvn -B test --file pom.xml
   
  
